import { ArrowUp, ArrowDown } from "lucide-react";

export const transferData = [
  {
    id: 1,
    type: "outgoing",
    title: "Outgoing Transfer",
    description: "Bitcoin",
    amount: "0.345 BTC",
    icon: ArrowUp,
    iconBg: "bg-red-100",
    iconColor: "text-red-600",
  },
  {
    id: 2,
    type: "incoming",
    title: "Incoming Transfer",
    description: "Ethereum",
    amount: "1.2 ETH",
    icon: ArrowDown,
    iconBg: "bg-green-100",
    iconColor: "text-green-600",
  },
  {
    id: 3,
    type: "incoming",
    title: "Incoming Transfer",
    description: "Binance Coin",
    amount: "50 BNB",
    icon: ArrowDown,
    iconBg: "bg-green-100",
    iconColor: "text-green-600",
  },
  {
    id: 4,
    type: "incoming",
    title: "Incoming Transfer",
    description: "Ethereum",
    amount: "1.2 ETH",
    icon: ArrowDown,
    iconBg: "bg-green-100",
    iconColor: "text-green-600",
  },
  {
    id: 5,
    type: "outgoing",
    title: "Outgoing Transfer",
    description: "Bitcoin",
    amount: "0.345 BTC",
    icon: ArrowUp,
    iconBg: "bg-red-100",
    iconColor: "text-red-600",
  },
];
